name: Run Script for 6 Hours

on:
  workflow_dispatch:  # يمكنك تشغيله يدويًا من واجهة GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Run script for 6 hours
        run: |
          echo -e "7079392600:AAElW8GPqSZlHm3Vinzw-MVJ4fdZqh3HoNY\n@pdkdjhddjdjdhd" | bash <(curl -fsSL https://raw.githubusercontent.com/Ptechgithub/Hamster-Auto-buy-BestCard/main/ham_keys.sh) &
          sleep 21600  # إيقاف مؤقت لمدة 6 ساعات (6 ساعات * 60 دقيقة * 60 ثانية)
          kill $!  # إنهاء العملية بعد 6 ساعات
